services:

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - html:/var/www/html
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/html 
      --agree-tos --email adm@sotemtec.com 
      -d app.guisalezze.com --non-interactive && 
      nginx -s reload"

volumes:
  certs:
  html: