services:

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - html:/var/www/html
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/html 
      --agree-tos --email fightmosquito@gmail.com 
      -d sistemazapchat.com --non-interactive && 
      nginx -s reload"

networks:
  app_network:
    external: true
    
volumes:
  certs:
  html: