const timeZones = [
    { value: "Pacific/Midway", descricao: "(GMT-11:00) Midway Island, Samoa" },
    { value: "Pacific/Honolulu", descricao: "(GMT-10:00) Hawaii" },
    { value: "America/Anchorage", descricao: "(GMT-09:00) Alaska" },
    { value: "America/Los_Angeles", descricao: "(GMT-08:00) Pacific Time (US & Canada)" },
    { value: "America/Tijuana", descricao: "(GMT-08:00) Tijuana, Baja California" },
    { value: "America/Denver", descricao: "(GMT-07:00) Mountain Time (US & Canada)" },
    { value: "America/Phoenix", descricao: "(GMT-07:00) Arizona" },
    { value: "America/Chicago", descricao: "(GMT-06:00) Central Time (US & Canada)" },
    { value: "America/Mexico_City", descricao: "(GMT-06:00) Mexico City" },
    { value: "America/New_York", descricao: "(GMT-05:00) Eastern Time (US & Canada)" },
    { value: "America/Bogota", descricao: "(GMT-05:00) Bogotá, Lima, Quito" },
    { value: "America/Caracas", descricao: "(GMT-04:30) Caracas" },
    { value: "America/Santiago", descricao: "(GMT-04:00) Santiago" },
    { value: "America/Argentina/Buenos_Aires", descricao: "(GMT-03:00) Buenos Aires" },
    { value: "America/Sao_Paulo", descricao: "(GMT-03:00) Brasília" },
    { value: "Atlantic/Azores", descricao: "(GMT-01:00) Azores" },
    { value: "Europe/London", descricao: "(GMT+00:00) London, Lisbon" },
    { value: "Europe/Berlin", descricao: "(GMT+01:00) Berlin, Madrid, Paris" },
    { value: "Europe/Athens", descricao: "(GMT+02:00) Athens, Bucharest, Istanbul" },
    { value: "Africa/Cairo", descricao: "(GMT+02:00) Cairo" },
    { value: "Asia/Jerusalem", descricao: "(GMT+02:00) Jerusalem" },
    { value: "Europe/Moscow", descricao: "(GMT+03:00) Moscow, St. Petersburg" },
    { value: "Asia/Dubai", descricao: "(GMT+04:00) Abu Dhabi, Dubai" },
    { value: "Asia/Kabul", descricao: "(GMT+04:30) Kabul" },
    { value: "Asia/Karachi", descricao: "(GMT+05:00) Islamabad, Karachi" },
    { value: "Asia/Kolkata", descricao: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
    { value: "Asia/Kathmandu", descricao: "(GMT+05:45) Kathmandu" },
    { value: "Asia/Dhaka", descricao: "(GMT+06:00) Dhaka" },
    { value: "Asia/Bangkok", descricao: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
    { value: "Asia/Shanghai", descricao: "(GMT+08:00) Beijing, Shanghai, Hong Kong" },
    { value: "Asia/Tokyo", descricao: "(GMT+09:00) Tokyo, Osaka" },
    { value: "Australia/Sydney", descricao: "(GMT+10:00) Sydney, Melbourne" },
    { value: "Pacific/Auckland", descricao: "(GMT+12:00) Auckland, Wellington" }
];

export default timeZones